/*
  Auto-generated by Spline
*/

import useSpline from '@splinetool/r3f-spline'
import { OrthographicCamera } from '@react-three/drei'


export default function Scene({ ...props }) {
  const { nodes, materials } = useSpline('https://draft.spline.design/PJNUKvfXHuIufwFZ/scene.splinecode')
  return (
    <>
      <color attach="background" args={['#42496f']} />
      <group {...props} dispose={null}>
        <OrthographicCamera
          name="Camera"
          makeDefault={true}
          zoom={0.44}
          far={100000}
          near={-100000}
          position={[-400, 10.74, 999.72]}
          rotation={[-0.01, 0.02, 0]}
          scale={1}
        />
        <mesh
          name="blob1 2"
          geometry={nodes['blob1 2'].geometry}
          material={materials['blob1 2 Material']}
          castShadow
          receiveShadow
          position={[28.38, 28.49, -820.62]}
        />
        <mesh
          name="blob1"
          geometry={nodes.blob1.geometry}
          material={materials['blob1 Material']}
          castShadow
          receiveShadow
          position={[-2, 14, 308]}
        />
        <directionalLight
          name="Directional Light"
          castShadow
          intensity={0.7}
          shadow-mapSize-width={1024}
          shadow-mapSize-height={1024}
          shadow-camera-near={-10000}
          shadow-camera-far={100000}
          shadow-camera-left={-500}
          shadow-camera-right={500}
          shadow-camera-top={500}
          shadow-camera-bottom={-500}
          position={[200, 300, 300]}
        />
        <hemisphereLight name="Default Ambient Light" intensity={0.75} color="#eaeaea" />
      </group>
    </>
  )
}
